version: '3'
services:
  mongo:
      ports:
      - "27017:27017"
      volumes:
      - ./data:/data/db
      image: mongo
  web:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo 