version: '3'
services:
  mongo:
      ports:
      - "27018:27018"
      volumes:
      - ./data:/data/db
      image: mongo
  web:
    build: .
    env_file:
    - .env
    ports:
    - "3001:3001"
    depends_on:
    - mongo 